export const ERR_USER_NOT_FOUND = 'USER_NOT_FOUND';
export const ERR_INVALID_PASSWORD = 'INVALID_PASSWORD';
export const ERR_INVALID_TOKEN = 'TOKEN_ERROR';
export const ERR_DUPLICATE_EMAIL = 'DUPLICATE_EMAIL';
